config/routes.rb
Rails.application.routes.draw do

  root 'page#welcome'

  resources :friendships, only: [:index, :create, :destroy] do
    member do
      post 'accept_friend/:id' => 'friendships#accept_friend', as: 'accept_friend'
      post 'decline_friend/:id' => 'friendships#decline_friend', as:'decline_friend'
    end
  end

 devise_for :users, controllers: { registrations: "registrations" }

 resources :users, only: [:show, :edit, :update]
 resources :allergies
 resources :ingredients
 resources :events

 delete 'decline_event/:id' => 'events#decline_event', as: 'decline_event'
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :user_ingredients, dependent: :destroy
  has_many :users, through: :user_ingredients

  validates :name, uniqueness: true
  validates :name, presence: true

  after_create :set_new_user_ingredients
  after_update :set_user_ingredients

  def set_user_ingredients
    if self.is_foodcategory_changed?
      if self.is_foodcategory_was
        #legacy_user_ingredients_relationships << UserIngredient.where(ingredient_id: self.id)
        #debugger
        #legacy_user_ingredients_relationships.each do |legacy_user_ingredients_relationships|
        #legacy_user_ingredients_relationship.destroy
        #end
        UserIngredient.where(ingredient_id: self.id).destroy_all
      else
        set_new_user_ingredients
      end
    end
  end

  def set_new_user_ingredients
    User.all.each do |user|
      UserIngredient.create(user_id: user.id, ingredient_id: self.id)
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to ingredients_path, notice: t('helpers.notices.create', :name => t('ingredients.ingredient')) }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html {
          flash.alert = t('ingredients.alerts.create', :name => t('ingredients.ingredient'))
          render :new  }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to ingredients_path, notice: t('helpers.notices.update', :name => t('ingredients.ingredient')) }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, alert: t('ingredients.alerts.create', :name => t('ingredients.ingredient')) }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_path, notice: t('helpers.notices.destroy', :name => t('ingredients.ingredient')) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :is_foodcategory)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
  def render_ingredient_edit_button(ingredient)
    link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe,  edit_ingredient_path(ingredient), class: 'btn btn-info'
  end

  def render_ingredient_destroy_button(ingredient)
        link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, ingredient, method: :delete, data: { confirm: t('helpers.prompts.delete', :name => ingredient.name) }, class: 'btn btn-danger'
  end

  def render_circle(is_foodcategory)
    if is_foodcategory
      '<p class="text-center"><span class="badge badge-success">Yes</span></p>'.html_safe
    else
      '<p class="text-center"><span class="badge badge-error">No</span></p>'.html_safe
    end
  end
end

app/views/ingredients/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <%= form_for(@ingredient) do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :is_foodcategory %>
          <%= f.check_box :is_foodcategory, class: 'checkbox' %>
        </div>

        <%= f.submit t('forms.buttons.submit'), class: 'btn btn-primary' %>

      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1 class="text-center"><%= t('ingredients.edit') %></h1>
  </div>
</div>
<%= render 'form' %>

app/views/ingredients/index.html.erb
<div class="container">
  <div class="page-header">
    <div class="row">
      <h1 class="text-center"><%= t('ingredients.ingredients') %></h1>
    </div>
     </div>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= t('misc.name') %></th>
            <th class="text-center"><%= t('misc.foodcategory') %></th>
            <th class="text-center"><%= t('forms.buttons.edit') %></th>
            <th class="text-center"><%= t('forms.buttons.destroy') %></th>
          </tr>
        </thead>
        <tbody>
          <% @ingredients.each do |ingredient| %>
            <tr>
              <td class="col-xs-6 col-sm-5 col-md-4 col-lg-4"><%= ingredient.name %></td>
              <td class="col-xs-6 col-sm-5 col-md-4 col-lg-2 text-center"><%= render_circle(ingredient.is_foodcategory) %></td>
              <td class="col-xs-2 col-sm-1 col-md-1 col-lg-1 text-center"><%= render_ingredient_edit_button(ingredient) %></td>
              <td class="col-xs-2 col-sm-1 col-md-1 col-lg-1 text-center"><%= render_ingredient_destroy_button(ingredient) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <p class="text-center"><%= t('ingredients.add') %></p>
    <div class="text-center">
      <%= link_to t('forms.buttons.new'), new_ingredient_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class="container">
  <div class="page-header">
    <h1 class="text-center"><%= t('ingredients.add_header') %></h1>
  </div>
</div>
<%= render 'form' %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>