config/routes.rb
Rails.application.routes.draw do

  root 'page#welcome'

  resources :friendships, only: [:index, :create, :destroy] do
    member do
      post 'accept_friend/:id' => 'friendships#accept_friend', as: 'accept_friend'
      post 'decline_friend/:id' => 'friendships#decline_friend', as:'decline_friend'
    end
  end

 devise_for :users, controllers: { registrations: "registrations" }

 resources :users, only: [:show, :edit, :update]
 resources :allergies
 resources :ingredients
 resources :events

 delete 'decline_event/:id' => 'events#decline_event', as: 'decline_event'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :user_events, dependent: :destroy
  has_many :users, through: :user_events
  belongs_to :creator, class_name: "User"

  validates :title,       presence: true
  validates :date,        presence: true
  validates :start_time,  presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy, :decline_event]
  before_action :set_friends, only: [:new, :edit, :create, :update]

  # GET /events
  # GET /events.json
  def index
    @my_events = Event.where(creator_id: current_user.id)
    @invitations = []
    user_events = UserEvent.where(user_id: current_user.id)

    user_events.each do |user_event|
      @invitations << Event.where("id = ? and creator_id != ?", user_event.event_id, current_user.id).first
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.creator_id = current_user.id
    @event.users = get_invited_friends_from_params

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, alert: 'Event could not be created.' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event.creator_id = current_user.id
    @event.users = get_invited_friends_from_params
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def decline_event
    debugger
    user_event = UserEvent.where("event_id = ? and user_id = ?", @event.id, current_user.id).first

    if user_event.destroy
      redirect_to events_url, notice: t('event.reject')
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def set_friends
      @friends = current_user.friends
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :date, :start_time, :end_time)
    end

    def invited_friends_params
      params[:event][:id]
    end

    def get_invited_friends_from_params
      User.where(id: invited_friends_params)
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def render_event_info_button(event)
    link_to "<i class='glyphicon glyphicon-info-sign'></i>".html_safe,  event_path(event), class: 'btn btn-info'
  end

  def render_event_edit_button(event)
    link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe, edit_event_path(event), class: 'btn btn-primary'
  end

  def render_event_destroy_button(event)
    link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, event, method: :delete, data: { confirm: t('helpers.prompts.delete', :name => event.title) }, class: 'btn btn-danger'
  end

  def render_not_participate_button(event)
    link_to  "<i class='glyphicon glyphicon-remove-sign'></i>".html_safe, decline_event_path(event), method: :delete, class: 'btn btn-warning'
  end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title,  class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", rows: "5" %>
      </div>
      <div class="form-group">
        <%= f.label :date %>
        <%= f.text_field :date, "data-provide" => 'datepicker', class: "form-control" %>
      </div>
      <div class="form-group text-center">
        <%= f.label :start_time %>
        <%= f.time_select :start_time %>
      </div>
      <div class="form-group text-center">
        <%= f.label :end_time %>
        <%= f.time_select :end_time %>
      </div>
    </div>
  </div>
  <div class="row">
    <h3 class="text-center"><%= t('events.select_friends') %></h3>
    <div class="col-xs-4 col-xs-offset-5 col-sm-4 col-sm-offset-5 col-md-4 col-md-offset-5 col-lg-4 col-lg-offset-5">
      <%= f.collection_check_boxes(:id, @friends, :id, :username) do |a| %>
        <div class="checkbox">
          <label>
            <%= a.check_box(class: "check_box", checked: @event.users.include?(a.object)) %><%= a.object.username %>
          </label>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row text-center">
    <%= f.submit t('forms.buttons.submit'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>
<div class="container">
  <div class="page-header">
    <h1 class="text-center"><%= t('events.edit_event') %></h1>
  </div>
  <%= render 'form' %>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="page-header">
    <div class="row">
      <h1 class="text-center"><%= t('events.my_events') %></h1>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <table class="table table-striped">
        <thead>
          <tr>
            <th class="text-center"><%= t('events.title') %></th>
            <th class="text-center"><%= t('events.date') %></th>
            <th class="text-center"><%= t('user.info') %></th>
            <th class="text-center"><%= t('forms.buttons.edit') %></th>
            <th class="text-center"><%= t('forms.buttons.destroy') %></th>
          </tr>
        </thead>
        <tbody>
          <% @my_events.each do |my_event| %>
            <tr>
              <td class="col-xs-5 col-sm-5 col-md-5 col-lg-5 text-center"><%= my_event.title %></td>
              <td class="col-xs-4 col-sm-4 col-md-4 col-lg-4 text-center"><%= my_event.date %></td>
              <td class="col-xs-1 col-sm-1 col-md-1 col-lg-1 text-center"><%= render_event_info_button(my_event) %></td>
              <td class="col-xs-1 col-sm-1 col-md-1 col-lg-1 text-center"><%= render_event_edit_button(my_event) %></td>
              <td class="col-xs-1 col-sm-1 col-md-1 col-lg-1 text-center"><%= render_event_destroy_button(my_event) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <p class="text-center"><%= t('events.add') %></p>
    <div class="text-center">
      <%= link_to t('forms.buttons.new'), new_event_path, class: 'btn btn-success' %>
    </div>
  </div>

  <div class="page-header">
    <div class="row">
      <h1 class="text-center"><%= t('events.invitations') %></h1>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <table class="table table-striped">
        <thead>
          <tr>
            <th class="text-center"><%= t('events.title') %></th>
            <th class="text-center"><%= t('events.date') %></th>
            <th class="text-center"><%= t('user.info') %></th>
            <th class="text-center"><%= t('forms.button.reject') %></th>
          </tr>
        </thead>
        <tbody>
          <% @invitations.each do |invitation| %>
            <tr>
              <td class="col-xs-5 col-sm-5 col-md-5 col-lg-5 text-center"><%= invitation.title %></td>
              <td class="col-xs-5 col-sm-5 col-md-5 col-lg-5 text-center"><%= invitation.date %></td>
              <td class="col-xs-1 col-sm-1 col-md-1 col-lg-1 text-center"><%= render_event_info_button(invitation) %></td>
              <td class="col-xs-1 col-sm-1 col-md-1 col-lg-1"><%= render_not_participate_button(invitation) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="page-header">
    <h1 class="text-center"><%= t('events.add_event') %></h1>
  </div>
  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="page-header">
    <div class="row">
      <h1 class="text-center"><%= @event.title %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3">
      <h5 class="text-center">Information:</h5>
      <p class="text-center">
      <%= @event.date.strftime("%d.%m.%Y") %>
      </p>
      <p class="text-center">
      <%= @event.start_time.strftime("%H:%M") %> - <%= @event.end_time.strftime("%H:%M") %>
      </p>
      <p class="text-center">
      <%= User.where(id: @event.creator_id).first.username %>
      </p>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8">
      <p><%= @event.description %></p>
    </div>
  </div>

  <div class="row">
    <h2 class="text-center"><%= t('events.participants') %></h2>
  </div>
  <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="text-center"><%= t('user.username') %></th>
          <th class="text-center"><%= t('user.first_name') %></th>
          <th class="text-center"><%= t('user.last_name') %></th>
        </tr>
      </thead>
      <tbody>
        <% @event.users.each do |user| %>
          <tr>
            <td class="text-center"><%= user.username %></td>
            <td class="text-center"><%= user.first_name%></td>
            <td class="text-center"><%= user.last_name%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>