config/routes.rb
Rails.application.routes.draw do

  root 'page#welcome'

  resources :friendships, only: [:index, :create, :destroy] do
    member do
      post 'accept_friend/:id' => 'friendships#accept_friend', as: 'accept_friend'
      post 'decline_friend/:id' => 'friendships#decline_friend', as:'decline_friend'
    end
  end

 devise_for :users, controllers: { registrations: "registrations" }

 resources :users, only: [:show, :edit, :update]
 resources :allergies
 resources :ingredients
 resources :events

 delete 'decline_event/:id' => 'events#decline_event', as: 'decline_event'
end

app/models/allergy.rb
class Allergy < ActiveRecord::Base
  has_many :user_allergy, dependent: :destroy
  has_many :users, through: :user_allergy
  validates :name, presence: true
end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController
  before_action :set_allergy, only: [:show, :edit, :update, :destroy]

  #TODO insert admin functionality
  #Only admins should be allowed to access allergies

  # GET /allergies
  # GET /allergies.json
  def index
    @allergies = Allergy.all
  end

  # GET /allergies/1
  # GET /allergies/1.json
  def show
  end

  # GET /allergies/new
  def new
    @allergy = Allergy.new
  end

  # GET /allergies/1/edit
  def edit
  end

  # POST /allergies
  # POST /allergies.json
  def create
    @allergy = Allergy.new(allergy_params)

    respond_to do |format|
      if @allergy.save
        format.html { redirect_to new_allergy_path, notice: t('allergies.created') }
        format.json { render :show, status: :created, location: @allergy }
      else
        format.html { render :new, alert: t('errors.messages.empty') }
        format.json { render json: @allergy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allergies/1
  # PATCH/PUT /allergies/1.json
  def update
    respond_to do |format|
      if @allergy.update(allergy_params)
        format.html { redirect_to @allergy, notice: t('allergies.update_success') }
        format.json { render :show, status: :ok, location: @allergy }
      else
        format.html { render :edit }
        format.json { render json: @allergy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allergies/1
  # DELETE /allergies/1.json
  def destroy
    @allergy.destroy
    respond_to do |format|
      format.html { redirect_to allergies_url, notice: t('allergies.destroy_success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allergy
      @allergy = Allergy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allergy_params
      params.require(:allergy).permit(:name)
    end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
  def render_allergy_edit_button(allergy)
    link_to "<i class='glyphicon glyphicon-pencil'></i>".html_safe,  edit_allergy_path(allergy), class: 'btn btn-info'
  end

  def render_allergy_destroy_button(allergy)
    link_to "<i class='glyphicon glyphicon-trash'></i>".html_safe, allergy, method: :delete, data: { confirm: t('helpers.prompts.delete', :name => allergy.name) }, class: 'btn btn-danger'
  end
end

app/views/allergies/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <%= form_for(@allergy) do |f| %>
        <div class="form-group">
          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="row text-center">
          <%= f.submit t('forms.buttons.submit'), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/allergies/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1 class="text-center"><%= t('allergies.edit_allergy') %></h1>
  </div>
</div>
<%= render 'form' %>

app/views/allergies/index.html.erb
<div class="container">
  <div class="page-header">
    <div class="row">
      <h1 class="text-center"><%= t('allergies.allergies_header') %></h1>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= t('allergies.name') %></th>
            <th><%= t('forms.buttons.edit') %></th>
            <th><%= t('forms.buttons.destroy') %></th>
          </tr>
        </thead>
        <tbody>
          <% @allergies.each do |allergy| %>
            <tr>
              <td class="col-xs-6 col-sm-6 col-md-4 col-lg-4"><%= allergy.name %></td>
              <td class="col-xs-2 col-sm-1 col-md-1 col-lg-1"><%= render_allergy_edit_button(allergy) %></td>
              <td class="col-xs-2 col-sm-1 col-md-1 col-lg-1"><%= render_allergy_destroy_button(allergy) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <p class="text-center"><%= t('allergies.add') %></p>
    <div class="text-center">
      <%= link_to t('forms.buttons.new'), new_allergy_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/allergies/new.html.erb
<div class="container">
  <div class="page-header">
    <h1 class="text-center"><%= t('allergies.add_allergy') %></h1>
  </div>
</div>

<%= render 'form' %>

app/views/allergies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @allergy.name %>
</p>

<%= link_to 'Edit', edit_allergy_path(@allergy) %> |
<%= link_to 'Back', allergies_path %>